config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints :subdomain => 'minecraft' do
  # scope module: 'minecraft' do
    root to: 'lander#index'
    get '/kart', to: 'lander#kart'
    get '/mapfolder', :to => redirect('/overviewer/')
  # end
  end

  constraints :subdomain => 'warp.eirik' do
    scope module: 'warp' do
      #routes for a viewer and new users
      root to: 'users#new'
      resources :users, only: [:new, :create] do
        get 'submit', to: 'levels#create', as: :submission
        get 'replace', to: 'levels#replace', as: :replacement
        get 'remove', to: 'levels#remove', as: :removal
#TO DO : implement levels#show
        resources :levels, only: [:index, :show] do
        end
      end

      # TO DO:
      # ajaxify
      # rename

      #routes for existing users
      scope ':api_key' do
        root to: 'users#edit', as: :queuer
        patch 'update', to: 'users#update', as: :update_queuer

        scope 'q' do  #for control of queue
          get 'enable', to: 'users#enable', as: :queue_open
          get 'disable', to: 'users#disable', as: :queue_close
          get 'clear', to: 'users#clear', as: :list_clear_all
          get 'play/:code', to: 'users#play', as: :queue_play
          #TO DO: below
          get 'timer', to: 'users#set_timer', as: :queue_timer
          get 'next', to: 'users#next', as: :queue_next
          get 'prev', to: 'users#prev', as: :queue_prev
        end
        scope 'c' do  #for streamer's controls in list
        get 'skip/:level_code/', to: 'users#skip', as: :skip_level
        get 'start/:level_code/', to: 'users#start', as: :start_level
        get 'complete/:level_code/', to: 'users#complete', as: :complete_level
        get 'remove/:level_code', to: 'users#remove', as: :remove_level
        get 'reset/:level_code', to: 'users#reset', as: :reset_level
        end
      end

    end
  end


end

app/models/warp.rb
module Warp
  def self.table_name_prefix
    'warp_'
  end
end

app/models/warp/level.rb
class Warp::Level < ApplicationRecord
  belongs_to :user
end

app/models/warp/user.rb
class Warp::User < ApplicationRecord
  has_many :levels
end

app/controllers/warp/levels_controller.rb
class Warp::LevelsController < ApplicationController
  
  
  def replace
    submitter = CGI::unescape params[:added_by]
    
    code = params[:code]
    pattern = /(([a-hj-np-yA-Z0-9]{3}-){2}[a-hj-np-yA-Z0-9]{3})/
    matches = code.match(pattern)
    if matches == nil or matches == [] then
      render plain: "Sorry, you must've misspelled - try again @#{submitter}!"      
      return
    end
    code = matches[0]
    
    warp_user = Warp::User.find params[:user_id]
	
    level = Warp::Level.find_by(added_by: submitter, user_id: warp_user.id, status: nil)
	if level == nil or level == [] then
      render plain: "Sorry, @#{submitter} - you've not submitted any replaceable levels recently!"
      return
    else
	  #["current", "skipped", "completed"].each do |s|
	  #  if s == level.status then
	  #    level
		  
		#  render :plain => nil
     #     return
    #    end
	 # end
    end
    
    level.code = code
    level.save
    
    render plain: "@#{submitter}, your most recent submission has been successfully replaced!"
    
  end
  
  # render plain: "Sorry, #{submitter} - that's not a level you've submitted! Try again."
  
  def remove
    submitter = CGI::unescape params[:added_by]
    
    code = params[:code]
    pattern = /(([a-hj-np-yA-Z0-9]{3}-){2}[a-hj-np-yA-Z0-9]{3})/
    matches = code.match(pattern)
    if matches == nil or matches == [] then
      render plain: "Sorry, you must've misspelled - try again @#{submitter}!"      
      return
    end
    code = matches[0]
    
    warp_user = Warp::User.find params[:user_id]
    
	# viewer has mistyped
    level = Warp::Level.find_by code: code
    if level == nil or level == [] then
      render plain: "Sorry, #{submitter} - that's not a level you've submitted -"
      return
    end
    
    # viewer has not submitted ANY levels
    level = Warp::Level.find_by user_id: warp_user.id, added_by: submitter, status: nil
    if level == nil or level == [] then
      render plain: "Sorry, @#{submitter} - you've not submitted any removable levels recently!"
      return
    end
    
	#
	
    level.destroy
    render plain: "@#{submitter}, your level (#{code}) has been successfully removed from the queue! But why? 😯"
    
  end
  
  
  
  # GET /warp/levels
  # GET /warp/levels.json
  def index
    @warp_user = Warp::User.find params[:user_id]
    @levels = @warp_user.levels
    #@warp_levels = Warp::Level.where user_id: @warp_user.id
  end


  # POST /warp/levels
  # POST /warp/levels.json
  def create
    submitter = CGI::unescape params[:added_by]
    user = Warp::User.find params[:user_id]
    #check if queue is closed or not
    if user.active == false then
      render plain: "Sorry, @#{submitter} - it seems like the submission queue has been closed for now!"
      return
    end
    code = params[:code]

    pattern = /(([a-hj-np-yA-Z0-9]{3}[-|\s]){2}[a-hj-np-yA-Z0-9]{3})/
    matches = code.match(pattern)
    if matches != nil then
      code = matches[0]
      warp_level = Warp::Level.where(code: code, user_id: user.id)
      if warp_level == nil or warp_level == [] then

      warp_level = Warp::Level.new
      warp_level.added_by = submitter
      warp_level.code = code
      warp_level.user_id = user.id
      warp_level.save
      
      render plain: "@#{submitter}, your level has been successfully added to our queue!"
      else
      render plain: "Sorry, @#{submitter}, it seems someone has added that level to the queue already!"
      end
    else
      render plain: "Sorry, you must've misspelled - try again @#{submitter}!"      
    end
    return
  
    

    respond_to do |format|
      if @warp_level.save
        format.html { redirect_to @warp_level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @warp_level }
      else
        format.html { render :new }
        format.json { render json: @warp_level.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warp_level
      @warp_level = Warp::Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def warp_level_params
      #params.require(:code, :added_by)
    end
end

app/controllers/warp/users_controller.rb
class Warp::UsersController < ApplicationController
  
  #before_action :set_warp_user, only: [:destroy]
  before_action :using_api_key, only: [:update, :enable, :disable, :play, :start, :remove, :skip, :complete, :reset, :clear]
  before_action :find_level, only: [:start, :complete, :skip, :reset, :remove]
  after_action :respond_to_submission_management, only: [:enable, :disable]
    
  def play     #unused
    code = params[:code]
    if code != nil then
      # change level
      @warp_user.current = Level.find_by(code: code)
      @warp_user.save
    end
  end

  
  def enable
    allow_submissions
  end
  def disable
    allow_submissions false
  end    
  def clear
    @warp_user.levels.destroy_all
  end



  def stop_timer level
    level.completed_at = Time.now
  end


  def start
    @previous = Warp::Level.find_by user_id: @warp_user.id, status: 'current'
	if @previous != nil then
      @previous.status = 'skipped'
	  stop_timer(@previous)
	  @previous.save
	end
	
	@level.status = 'current'
    @level.started_at = Time.now
    @level.save
  end
  
  def remove
    @level.destroy
  end
  
  def reset
    @level.status = nil
    @level.started_at = nil
    @level.completed_at = nil
    @level.save
  end
  
  
  def complete
    @level.status = "completed"
    stop_timer @level
    @level.save
  end
  
  def skip
    @level.status = "skipped"
    stop_timer @level
    @level.save
  end
  
  # GET /warp/users
  # GET /warp/users.json
  def index
    @warp_users = Warp::User.all
  end


  # GET /warp/users/new
  def new
    @warp_user = Warp::User.new
  end

  # GET /warp/users/1/edit
  def edit
    @warp_user = Warp::User.find_by(api_key: params[:api_key])
    if @warp_user == nil then
      render plain: "Sorry, but you either haven't signed up, or you've mistyped. P:"
      return
    end
    @levels = Warp::Level.find @warp_user.level_ids  
  end

  # POST /warp/users
  # POST /warp/users.json
  def create
    @warp_user = Warp::User.new(warp_user_params)

    respond_to do |format|
      if @warp_user.save
        format.html { redirect_to queuer_path(@warp_user.api_key), notice: 'User was successfully created.' }
        #format.json { render :show, status: :created, location: @warp_user }
      else
        format.html { render :new }
        #format.json { render json: @warp_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warp/users/1
  # PATCH/PUT /warp/users/1.json
  def update
    new_name = params[:new_name]
    new_key = params[:new_key]
    @warp_user.channel_name = new_name
    @warp_user.api_key = new_key
    @warp_user.save
    respond_to do |format|
        format.html { redirect_to queuer_path(@warp_user.api_key), notice: 'User was successfully updated.' }
    end
  end

  # DELETE /warp/users/1
  # DELETE /warp/users/1.json
  def destroy
    @warp_user.destroy
    respond_to do |format|
      format.html { redirect_to warp_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warp_user
      @warp_user = Warp::User.find(params[:id])
    end
    def using_api_key
      @warp_user = Warp::User.find_by api_key: params[:api_key]
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def warp_user_params
      params.require(:warp_user).permit(:api_key, :channel_name)
    end


	# allow / deny level submissions
    def allow_submissions(bool=true)
      @warp_user.active = bool
      @warp_user.save
    end
    def respond_to_submission_management
      @active = @warp_user.active
    end
	
	# for interacting with a level
	def find_level
      @level = Warp::Level.find_by user_id: @warp_user.id, code: params[:level_code]
	end
end

app/helpers/warp/levels_helper.rb
module Warp::LevelsHelper
end

app/helpers/warp/users_helper.rb
module Warp::UsersHelper
end

app/views/warp/users/_bot_info.html.erb
<style>
  .child {
    scroll-snap-align: start;
  }

    code {background-color: black;
      color: white;}
</style>

<div class="container" style="display: flex; overflow-x:auto;scroll-snap-type: y mandatory;">
  <div class="container col-md-6">
    <section class="child">

      <h3>Nightbot integration</h3>

      Just paste these into your <strong>Nightbot</strong> commands:<br/>
      <p>
        Submissions (<i>e.g. !add</i>):&nbsp;
        <strong>
          <code>
            $(urlfetch <%= user_submission_url(usr) %>?added_by=$(eval encodeURIComponent(`$(user)`);)&code=$(querystring))
          </code></strong><br>
      </p>
      <p>
        Replacements (<i>e.g. !exch</i>):&nbsp;
        <strong>
          <code>
            $(urlfetch <%= user_replacement_url(usr) %>?added_by=$(eval encodeURIComponent(`$(user)`);)&code=$(querystring))
          </code></strong><br>
      </p>
      <p>
        Removals (<i>e.g. !del</i>):&nbsp;
        <strong>
          <code>
            $(urlfetch <%= user_removal_url(usr) %>?added_by=$(eval encodeURIComponent(`$(user)`);)&code=$(querystring))
          </code></strong><br>
      </p>
    </section>
  </div>
  <div class="container col-md-6">
    <section class="child">
      <h3>Botisimo integration</h3>

      Just paste these into your <strong>Botisimo</strong> commands:<br/>
      <p>
        Submissions (<i>e.g. !add</i>):&nbsp;
        <strong>
          <code>
            $(fetch <%= user_submission_url(usr) %>?added_by=$(urlencode $(usernameplain))&code=$(query))
          </code></strong><br>
      </p>
      <p>
        Replacements (<i>e.g. !exch</i>):&nbsp;
        <strong>
          <code>
            $(fetch <%= user_replacement_url(usr) %>?added_by=$(urlencode $(usernameplain))&code=$(query))
          </code></strong><br>
      </p>
      <p>
        Removals (<i>e.g. !del</i>):&nbsp;
        <strong>
          <code>
            $(fetch <%= user_removal_url(usr) %>?added_by=$(urlencode $(usernameplain))&code=$(query))
          </code></strong><br>
      </p>
      <p>

    </section>
  </div>
  <div class="container col-md-6">
    <section class="child">
      oogf :3
    </section>
  </div>
</div>

app/views/warp/users/_faucet.html.erb
<input id="faucet-input" type="checkbox" <% if @warp_user.active %>checked="true"<% end %>>

<script type="text/javascript">
  function faucet_change_url ()
  {
    var f = $('#faucet-input').prop('checked');
    var url = window.location;
    const has_trailing_slash = (s) => /^.*\/$/.test(s);
    if (!has_trailing_slash(url)) {
      url += '/';
    }

    url += f ? 'q/enable' : 'q/disable';
	$('#sub-mgmt-spinner').show();
    $.get(url, function(){});
  }

  $('#faucet-input').change(function(){;faucet_change_url();});


  function load_faucet(id, v) {
    $(id).prop('checked', v);
    <% txt = "Levels can not be submitted to the queue" %>
    <% if @warp_user.active then %>
    <% txt="Levels can be submitted to the queue" %>
    <% end %>
  }
  $(function() {
    var j = $('#faucet-input');
    j.bootstrapToggle({
      on: "OPEN",
      off: "CLOSED",
      onstyle: "success",
      offstyle: "danger",
      size: 'large'
      });
    });
</script>

app/views/warp/users/_form.html.erb
<%= form_for @warp_user, method: 'post', url: users_path do |form| %>

  
  <div class="field">
    <strong><%= form.label :channel_name %></strong>
    <%= form.text_field :channel_name %>
  </div>
    
  <div class="field">
    <strong>
	  <%= form.label :api_key do |label|%>key (our secret)<% end %>
	</strong><br>
    <%= form.text_field :api_key %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warp/users/_formus.html.erb
<%= form_tag update_queuer_path(@warp_user.api_key), :method => 'patch' do |form| %>

  
  <div class="field">
    <strong><%= label_tag :new_name %></strong>
    <%= text_field_tag :new_name %>
  </div>
    
  <div class="field">
    <strong><%= label_tag :new_key do |label|%>key (our secret)<% end %></strong><br>
    <%= text_field_tag :new_key %>
  </div>
  
  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/warp/users/complete.js.erb
level_finish('<%= @level.code %>');


$('#level-list-spinner').hide();

app/views/warp/users/disable.js.erb
$('#sub-mgmt-spinner').hide();

app/views/warp/users/edit.html.erb
<style>
  body {
    background-color: #ecbb00;
    font-family: verdana, arial, helvetica, sans-serif;
    font-weight: bold;
    color: white;
  }
  .zoomer { transition: transform .2s; }
  .zoomer:hover { transform: scale(1.2); }

  i.fas{
    color:white;
  }
  .level-card{
    background-color: #c19c00;
    margin-bottom: 32px;
  }
  .level-card.card-header {
    background-color:#8e7000;
  }

  .settings-card {
    background-color: #f9db00;
    margin-bottom: 32px;
    color: #c19c00;
  }
  .settings-card.card-header {
    color: white;
  }
.level-finished
{
background-color: rgba(0,0,0,0.3);
}
.level-current
{
background-color:rgba(255,0,0,0.3);
}

.blurred-out{
style="color: transparent; text-shadow: 0 0 9.5px rgba(0,0,0,0.5);
}

</style>

<div class="container-fluid row">

  <div class="col-lg-2">
    &nbsp;
  </div>

  <div class="col-xs-6 col-lg-8">
    <div class="card settings-card">
	
      <div class="card-header settings-card">
        <h1>Hello, <strong><%= @warp_user.channel_name %>!</h1></strong>
      </div>
      <div class="card-body settings-card">
        <p>
          Linking to your queue, for viewers to see:&nbsp;
          <strong><code>
            <%= user_levels_url(@warp_user) %>
          </code></strong>
        </p>

        <%= render("bot_info", usr: @warp_user) %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6 col-md-6">
	
        <div class="card settings-card">
          <div class="card-header settings-card">
            <strong><h3>
              Editing your user info
            </h3></strong>
          </div>
		
          <div class="card-body settings-card">
            <%= render "formus", warp_user: @warp_user %>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-6">
        <div class="card settings-card">
          <div class="card-header settings-card">
            <strong><h3>Submission management <span style="text-align:'right';"><i id="sub-mgmt-spinner" style="display: none;" class="fa fa-spin fa-spinner"></i></span></h3></strong>
          </div>
        <div class="card-body settings-card">
          <p style="text-align: center;">
            <%= render "faucet" %>
          </p>
          <% empty = @levels == nil or @levels == []%>
          <% if empty then %>
          <p>
            <strong>The queue is empty</strong>
          </p>
          <% else %>

          <p>
            <strong>Clear all levels from queue:</strong>&nbsp;
            <%#= link_to list_clear_all_url(@warp_user.api_key) %>
            <button id="sub-mgmt-clear-btn" type="button">Commit</button>
          <%# end %>
          </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<script>

$('#sub-mgmt-clear-btn').click( function () {
  $('#sub-mgmt-spinner').show();
  $.get('<%= list_clear_all_url(@warp_user.api_key) %>');
});

</script>


<div class="card settings-card">
	
      <div class="card-header settings-card">
        <h1>Level submissions<span style="text-align:right;"><i id="level-list-spinner" class="fas fa-spin fa-spinner" style="display:none;"></i></span></h1>
      </div>
      <div class="card-body settings-card">




<!-- #f9db00 -->

<p>
  <table border="2">
    <thead>
    <strong>
      <tr>
        <td>Current level?</td>
        <td>Time spent</td>
        <td>&nbsp;</td>
        <td>Added by</td>
        <td>Status</td>
        <td>Time since submission</td>

        <td>&nbsp;</td>
        <td>Level code</td>
        <td>&nbsp;</td>

        <td>Play</td>
        <td>Skip</td>
        <td>Complete</td>
        <td>Reset</td>
        <td>&nbsp;</td>
        <td>Delete</td>
      </tr>
    </strong>
  </thead>
  
  <script>

function level_by_code(code)
{
return $('#level-list-row-'+code);
}

function level_reset(code)
{
var o = level_by_code(code);
o.removeClass('level-current');
o.removeClass('level-finished');
o.addClass('blurred-out');
return o;
}

function level_finish(code)
{
var o = level_reset(code);
o.addClass('level-finished');
}
function level_begin(code)
{
var o = level_reset(code);
o.addClass('level-current');
o.removeClass('blurred-out');

}




    function c(content)
	{
	  return '<td>' + content + '</td>';
	}
function url_for(method, obj)
{
  var s = window.location;
  
  s += '/c/' + method + '/' + obj;
  return s;
}
function url_from_id(id)
{
var code = id.split('-');
var method = code.pop();
code = code.join('-');

return url_for(method, code);

}
function buttons_for_row(level)
{
  var s = "";
  s += c('<div id="'+level+'-start" class="btn level-list-control"><i class="fas fa-play"></i></div>');
  s += c('<div id="'+level+'-skip" class="btn level-list-control"><i class="fas fa-fast-forward"></i></div>');
  s += c('<div id="'+level+'-complete" class="btn level-list-control"><i class="fas fa-stop"></i></div>');
  s += c('<div id="'+level+'-reset" class="btn level-list-control""><i aria-hidden="true" class="fa fas fa-refresh"></i></div>');
  s += c('');
  s += c('<div id="'+level+'-remove" class="btn level-list-control"><i class="fas fa-trash"></i></div>');
  return s;
}


    function create_row(id, status, timestamp1, timestamp2, user, level)
	{
          var clr = '';
if( status == 'skipped' || status == 'completed'){
  clr = 'class="level-finished blurred-out"';
}else if (status == 'current') {
  clr = 'class="level-current"';
}

	  var s = '<tr id=\"level-list-row-' + level + '\"' + clr+'>';
	  s += c(status == 'current'?'<i class="fas fa-thumbs-up"></i>':'');
	  s += c(timestamp2);
	  s += c('');
	  s += c(user);
	  s += c(status);
	  s += c(timestamp1);
	  s += c('');
	  s += c(level);
	  s += c('');
	  s += buttons_for_row(level);
	  	
	  s += '</tr>';
	  return s;
	}
  
	$(document).ready(
	function(){
	
	
	var s = $('#level-list').html();
	<% @levels.each do |l| %>
      s += create_row(<%=l.id%>,'<%=l.status == nil ? "" : l.status%>','<%=l.created_at%>','<%=l.started_at%>','<%=l.added_by%>','<%=l.code%>');
	<%end%>
	$('#level-list').html(s);
	$('.level-list-control').click( function(){
	  $('#level-list-spinner').show();
$.get(url_from_id(this.id));

	});
	});


	</script>
  <tbody id="level-list">
  </tbody>
	<!--
	<tr>
      <td><%# if l.status == "current" then %><i class="fas fa-thumbs-up"></i><%#end%> </td>
      <td><strong>
        <%# if l.status == "current" then %>
        <%#= distance_of_time_in_words_to_now l.started_at %></strong></td>
        <%# else %>
        <%# if l.started_at != nil and l.completed_at != nil then %>
        <%#= distance_of_time_in_words (l.completed_at - l.started_at) %>
        <%# end %>
        <%# end %>
        <td>&nbsp;</td>

        <td><strong><%#= l.added_by %></strong></td>
        <td><%#= l.status %></td>
        <td><%#= distance_of_time_in_words_to_now(l.created_at) %></td>

        <td>&nbsp;</td>        
		<td><div style="color: transparent; text-shadow: 0 0 4.5px rgba(0,0,0,0.5);"><%#= l.code %></div></td>
        
		<td>&nbsp;</td>

        <td><%#= link_to start_level_path(@warp_user.api_key, l.code) do |link| %>
            <i class="fas fa-play"></i>
          <%# end %>
        </td>

        <td><%#= link_to skip_level_path(@warp_user.api_key, l.code) do |link| %>
            <i class="fas fa-forward"></i>
          <%# end %></td>

        <td><%#= link_to complete_level_path(@warp_user.api_key, l.code) do |link| %>
            <i class="fas fa-check"></i>
          <%# end %></td>

        <td><%#= link_to reset_level_path(@warp_user.api_key, @levels.take().code) do |link| %>
            <i class="fas fa-undo"></i>
          <%# end %></td>

        <td>&nbsp;</td>
        
		<td><%#= link_to remove_level_path(@warp_user.api_key, l.code) do |link| %>
            <i class="fas fa-trash"></i>
            <%# end %></td>

      </tr>
      <%# end %>
    <!-- </tbody> -->
  </table>
</p>
</div>
</div>


</div>
</div>

app/views/warp/users/enable.js.erb
$('#sub-mgmt-spinner').hide();

app/views/warp/users/new.html.erb
<h1>Warp Wørld</h1>

<p>
This website is a quick hack that provides super basic services for <strong>Super Mario Maker 2</strong> similar to that of <strong>Warp.World</strong><br>
When having signed in, you can create a bookmark for the page using your web browser, and never have to sign in manually again.<br>
<br>

</p>

<p>
<i>updated 15/07/19 </i><br>
<b>supports for Nightbot and Botisimo:</b><br>
 - level submission<br>
 - level replacement<br>
 - level removal<br>
<b>allows queuer to do:</b> <br>
 - play level, seeing elapsed time<br>
 - skip level<br>
 - complete level, storing time spent<br>
 - remove level<br>
 - empty queue<br>
 - open and close queue<br>
</p>

<p>
<strong>Notice: </strong> this site asks you to preferrably provide your streaming API key. The secret one provided to you by e.g. Youtube or Twitch. This is used in order to uniquely identify you.<br>
Also out of lazyness - but do not worry, <strike>API keys are encrypted when stored in our database, that way I can't read them.</strike>.<br>
You secret is in safe hands - though alternatively, you can just use a regular phony password (though you'd best guarantee it be a unique identifier). 
</p>

<p>
<i>
If you have <b>questions</b>, <b>suggestions</b> for features, or the like - do not hesitate to send me an email or hit me up on Discord.<br>
<strong>Discord:</strong> eirik#2638<br>
<strong>E-mail:</strong> jenssen.eirik@gmail.com <br>
</i>
</p>
<hr>
<h1>Sign in as existing user</h1>
<strong>API key</strong><br>
<input type="text" id="sign-in-field">
<button type="button" onclick="document.location = '/' + document.getElementById('sign-in-field').value;">Sign in</button>

<hr>
<h1>Create new Warp Wørld user</h1>



<%= render 'form', warp_user: @warp_user %>

app/views/warp/users/play.js.erb
alert("playing <%= @code %>");

app/views/warp/users/remove.js.erb
$('#level-list-row-<%= @level.code %>').remove();

$('#level-list-spinner').hide();

app/views/warp/users/reset.js.erb
level_reset('<%= @level.code %>');
$('#level-list-spinner').hide();

app/views/warp/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_warp_user_path(@warp_user) %> |
<%= link_to 'Back', warp_users_path %>

app/views/warp/users/start.js.erb
<% if @previous != nil then %>
level_finish('<%= @previous.code %>');
<% end %>

level_begin('<%= @level.code %>');


$('#level-list-spinner').hide();