config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints :subdomain => 'minecraft' do
  # scope module: 'minecraft' do
    root to: 'lander#index'
    get '/kart', to: 'lander#kart'
    get '/mapfolder', :to => redirect('/overviewer/')
  # end
  end

  constraints :subdomain => 'warp.eirik' do
    scope module: 'warp' do
      #routes for a viewer and new users
      root to: 'users#new'
      resources :users, only: [:new, :create] do
        get 'submit', to: 'levels#create', as: :submission
        get 'replace', to: 'levels#replace', as: :replacement
        get 'remove', to: 'levels#remove', as: :removal
#TO DO : implement levels#show
        resources :levels, only: [:index, :show] do
        end
      end

      # TO DO:
      # ajaxify
      # rename

      #routes for existing users
      scope ':api_key' do
        root to: 'users#edit', as: :queuer
        patch 'update', to: 'users#update', as: :update_queuer

        scope 'q' do  #for control of queue
          get 'enable', to: 'users#enable', as: :queue_open
          get 'disable', to: 'users#disable', as: :queue_close
          get 'clear', to: 'users#clear', as: :list_clear_all
          get 'play/:code', to: 'users#play', as: :queue_play
          #TO DO: below
          get 'timer', to: 'users#set_timer', as: :queue_timer
          get 'next', to: 'users#next', as: :queue_next
          get 'prev', to: 'users#prev', as: :queue_prev
        end
        scope 'c' do  #for streamer's controls in list
        get 'skip/:level_code/', to: 'users#skip', as: :skip_level
        get 'start/:level_code/', to: 'users#start', as: :start_level
        get 'complete/:level_code/', to: 'users#complete', as: :complete_level
        get 'remove/:level_code', to: 'users#remove', as: :remove_level
        get 'reset/:level_code', to: 'users#reset', as: :reset_level
        end
      end

    end
  end


end

app/models/warp.rb
module Warp
  def self.table_name_prefix
    'warp_'
  end
end

app/models/warp/level.rb
class Warp::Level < ApplicationRecord
  belongs_to :user
end

app/models/warp/user.rb
class Warp::User < ApplicationRecord
  has_many :levels
end

app/controllers/warp/levels_controller.rb
class Warp::LevelsController < ApplicationController
  
  
  def replace
    submitter = CGI::unescape params[:added_by]
    
    code = params[:code]
    pattern = /(([a-hj-np-yA-Z0-9]{3}-){2}[a-hj-np-yA-Z0-9]{3})/
    matches = code.match(pattern)
    if matches == nil or matches == [] then
      render plain: "Sorry, you must've misspelled - try again @#{submitter}!"      
      return
    end
    code = matches[0]
    
    warp_user = Warp::User.find params[:user_id]
	
    level = Warp::Level.find_by(added_by: submitter, user_id: warp_user.id, status: nil)
	if level == nil or level == [] then
      render plain: "Sorry, @#{submitter} - you've not submitted any replaceable levels recently!"
      return
    else
	  #["current", "skipped", "completed"].each do |s|
	  #  if s == level.status then
	  #    level
		  
		#  render :plain => nil
     #     return
    #    end
	 # end
    end
    
    level.code = code
    level.save
    
    render plain: "@#{submitter}, your most recent submission has been successfully replaced!"
    
  end
  
  # render plain: "Sorry, #{submitter} - that's not a level you've submitted! Try again."
  
  def remove
    submitter = CGI::unescape params[:added_by]
    
    code = params[:code]
    pattern = /(([a-hj-np-yA-Z0-9]{3}-){2}[a-hj-np-yA-Z0-9]{3})/
    matches = code.match(pattern)
    if matches == nil or matches == [] then
      render plain: "Sorry, you must've misspelled - try again @#{submitter}!"      
      return
    end
    code = matches[0]
    
    warp_user = Warp::User.find params[:user_id]
    
	# viewer has mistyped
    level = Warp::Level.find_by code: code
    if level == nil or level == [] then
      render plain: "Sorry, #{submitter} - that's not a level you've submitted -"
      return
    end
    
    # viewer has not submitted ANY levels
    level = Warp::Level.find_by user_id: warp_user.id, added_by: submitter, status: nil
    if level == nil or level == [] then
      render plain: "Sorry, @#{submitter} - you've not submitted any removable levels recently!"
      return
    end
    
	#
	
    level.destroy
    render plain: "@#{submitter}, your level (#{code}) has been successfully removed from the queue! But why? 😯"
    
  end
  
  
  
  # GET /warp/levels
  # GET /warp/levels.json
  def index
    @warp_user = Warp::User.find params[:user_id]
    @levels = @warp_user.levels
    #@warp_levels = Warp::Level.where user_id: @warp_user.id
  end


  # POST /warp/levels
  # POST /warp/levels.json
  def create
    submitter = CGI::unescape params[:added_by]
    user = Warp::User.find params[:user_id]
    #check if queue is closed or not
    if user.active == false then
      render plain: "Sorry, @#{submitter} - it seems like the submission queue has been closed for now!"
      return
    end
    code = params[:code]

    pattern = /(([a-hj-np-yA-Z0-9]{3}[-|\s]){2}[a-hj-np-yA-Z0-9]{3})/
    matches = code.match(pattern)
    if matches != nil then
      code = matches[0]
      warp_level = Warp::Level.where(code: code, user_id: user.id)
      if warp_level == nil or warp_level == [] then

      warp_level = Warp::Level.new
      warp_level.added_by = submitter
      warp_level.code = code
      warp_level.user_id = user.id
      warp_level.save
      
      render plain: "@#{submitter}, your level has been successfully added to our queue!"
      else
      render plain: "Sorry, @#{submitter}, it seems someone has added that level to the queue already!"
      end
    else
      render plain: "Sorry, you must've misspelled - try again @#{submitter}!"      
    end
    return
  
    

    respond_to do |format|
      if @warp_level.save
        format.html { redirect_to @warp_level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @warp_level }
      else
        format.html { render :new }
        format.json { render json: @warp_level.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warp_level
      @warp_level = Warp::Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def warp_level_params
      #params.require(:code, :added_by)
    end
end

app/controllers/warp/users_controller.rb
class Warp::UsersController < ApplicationController
  
  #before_action :set_warp_user, only: [:destroy]
  before_action :using_api_key, only: [:update, :enable, :disable, :play, :start, :remove, :skip, :complete, :reset, :clear]
  before_action :find_level, only: [:start, :complete, :skip, :reset, :remove]
  after_action :respond_to_submission_management, only: [:enable, :disable]
    
  def play     #unused
    code = params[:code]
    if code != nil then
      # change level
      @warp_user.current = Level.find_by(code: code)
      @warp_user.save
    end
  end

  
  def enable
    allow_submissions
  end
  def disable
    allow_submissions false
  end    
  def clear
    @warp_user.levels.destroy_all
  end



  def stop_timer level
    level.completed_at = Time.now
  end


  def start
    @previous = Warp::Level.find_by user_id: @warp_user.id, status: 'current'
	if @previous != nil then
      @previous.status = 'skipped'
	  stop_timer(@previous)
	  @previous.save
	end
	
	@level.status = 'current'
    @level.started_at = Time.now
    @level.save
  end
  
  def remove
    @level.destroy
  end
  
  def reset
    @level.status = nil
    @level.started_at = nil
    @level.completed_at = nil
    @level.save
  end
  
  
  def complete
    @level.status = "completed"
    stop_timer @level
    @level.save
  end
  
  def skip
    @level.status = "skipped"
    stop_timer @level
    @level.save
  end
  
  # GET /warp/users
  # GET /warp/users.json
  def index
    @warp_users = Warp::User.all
  end


  # GET /warp/users/new
  def new
    @warp_user = Warp::User.new
  end

  # GET /warp/users/1/edit
  def edit
    @warp_user = Warp::User.find_by(api_key: params[:api_key])
    if @warp_user == nil then
      render plain: "Sorry, but you either haven't signed up, or you've mistyped. P:"
      return
    end
    @levels = Warp::Level.find @warp_user.level_ids  
  end

  # POST /warp/users
  # POST /warp/users.json
  def create
    @warp_user = Warp::User.new(warp_user_params)

    respond_to do |format|
      if @warp_user.save
        format.html { redirect_to queuer_path(@warp_user.api_key), notice: 'User was successfully created.' }
        #format.json { render :show, status: :created, location: @warp_user }
      else
        format.html { render :new }
        #format.json { render json: @warp_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warp/users/1
  # PATCH/PUT /warp/users/1.json
  def update
    new_name = params[:new_name]
    new_key = params[:new_key]
    @warp_user.channel_name = new_name
    @warp_user.api_key = new_key
    @warp_user.save
    respond_to do |format|
        format.html { redirect_to queuer_path(@warp_user.api_key), notice: 'User was successfully updated.' }
    end
  end

  # DELETE /warp/users/1
  # DELETE /warp/users/1.json
  def destroy
    @warp_user.destroy
    respond_to do |format|
      format.html { redirect_to warp_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warp_user
      @warp_user = Warp::User.find(params[:id])
    end
    def using_api_key
      @warp_user = Warp::User.find_by api_key: params[:api_key]
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def warp_user_params
      params.require(:warp_user).permit(:api_key, :channel_name)
    end


	# allow / deny level submissions
    def allow_submissions(bool=true)
      @warp_user.active = bool
      @warp_user.save
    end
    def respond_to_submission_management
      @active = @warp_user.active
    end
	
	# for interacting with a level
	def find_level
      @level = Warp::Level.find_by user_id: @warp_user.id, code: params[:level_code]
	end
end

app/helpers/warp/levels_helper.rb
module Warp::LevelsHelper
end

app/helpers/warp/users_helper.rb
module Warp::UsersHelper
end

app/views/warp/levels/_form.html.erb
<%= form_with(model: warp_user_level, local: true) do |form| %>
  <% if warp_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warp_level.errors.count, "error") %> prohibited this warp_level from being saved:</h2>

      <ul>
      <% warp_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warp/levels/index.html.erb

<style>

  body {
    background-color: midnightblue;
 /*   font-family: Avenir, "Open Sans", "Helvetica Neue", Helvetica, Arial, Verdana, Roboto, "游ゴシック", "Yu Gothic", "游ゴシック体", "YuGothic", "ヒラギノ角ゴ Pro W3", "Hiragino Kaku Gothic Pro", "Meiryo UI", "メイリオ", Meiryo, "ＭＳ Ｐゴシック", "MS PGothic", sans-serif;
  */
  }
  .card-header.bg-primary{

    background-color : #f9db00;
  }
  .card-body.bg-primary, .card.bg-primary {
    background-color : #ecbb00, !important;
    font-weight: bold;

/*    font-family: Avenir, "Open Sans", "Helvetica Neue", Helvetica, Arial, Verdana, Roboto, "游ゴシック", "Yu Gothic", "游ゴシック体", "YuGothic", "ヒラギノ角ゴ Pro W3", "Hiragino Kaku Gothic Pro", "Meiryo UI", "メイリオ", Meiryo, "ＭＳ Ｐゴシック", "MS PGothic", sans-serif;
  */
  }




</style>

<div class="container-fluid"><div class="row">

  <div class="col-sm-2 col-lg-3"></div>

  <div class="col-sm-6 container">
    <div class="card">
    <div class="card-header">
      <h1>Level queue for channel "<%= @warp_user.channel_name %>"</h1><br>
      <h1 style="font-weight:bold;font-family: Arial">Level queue for channel "<%= @warp_user.channel_name %>"</h1>

    </div>
    <div class="card-body">


<p>
<strong>
Levels are listed in the order the were submitted.
</strong>
</p>

<hr/>

<% if @levels == nil or @levels == [] then %>
<p>
<strong>The queue is empty</strong>
</p>
<% else %>


<p>
<table border="2">
<thead>
<strong>
<tr>
<td>Current level?</td>
<td>Time since submission</td>
<td>Added by</td>

<td>&nbsp;</td>
<td>Level code</td>
<td>&nbsp;</td>
<td>Status</td>
</tr>
</strong>
</thead>
<tbody>
<% @levels.each do |l| %>

<tr>
<td><% if l.status == "current" then %><i class="fas fa-thumbs-up"></i><%end%> </td>
<td><%= distance_of_time_in_words_to_now(l.created_at) %></td>
<td><strong><%= l.added_by %></strong></td>

<td>&nbsp;</td>
<td><strong><%= l.code %></strong></td>
<td>&nbsp;</td>
<td><%= l.status %></td>
</tr>



<% end %>
</tbody>
</table>
</p>
<% end %>
    </div>
    </div>
  </div>

  <div class="col-sm-2 col-lg-3"></div>
</div></div>

app/views/warp/levels/new.html.erb
<h1>New Warp Level</h1>

<%= render 'form', warp_level: @warp_level %>

<%= link_to 'Back', warp_levels_path %>